# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PipeNetwork_GUI_New.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(2331, 1395)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.setFont(font)
        Form.setMouseTracking(True)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.grp_PipeAndNodeCreation = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grp_PipeAndNodeCreation.sizePolicy().hasHeightForWidth())
        self.grp_PipeAndNodeCreation.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.grp_PipeAndNodeCreation.setFont(font)
        self.grp_PipeAndNodeCreation.setMouseTracking(True)
        self.grp_PipeAndNodeCreation.setTitle("")
        self.grp_PipeAndNodeCreation.setObjectName("grp_PipeAndNodeCreation")
        self.gridLayout = QtWidgets.QGridLayout(self.grp_PipeAndNodeCreation)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label = QtWidgets.QLabel(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 242, 194);\n"
"")
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(3)
        self.label.setObjectName("label")
        self.verticalLayout_8.addWidget(self.label)
        self.table_Pipes = QtWidgets.QTableWidget(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_Pipes.sizePolicy().hasHeightForWidth())
        self.table_Pipes.setSizePolicy(sizePolicy)
        self.table_Pipes.setMinimumSize(QtCore.QSize(500, 0))
        self.table_Pipes.setMaximumSize(QtCore.QSize(1000, 500))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.table_Pipes.setFont(font)
        self.table_Pipes.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_Pipes.setAlternatingRowColors(True)
        self.table_Pipes.setRowCount(3)
        self.table_Pipes.setObjectName("table_Pipes")
        self.table_Pipes.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.table_Pipes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.table_Pipes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.table_Pipes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.table_Pipes.setHorizontalHeaderItem(3, item)
        self.table_Pipes.horizontalHeader().setDefaultSectionSize(65)
        self.table_Pipes.horizontalHeader().setMinimumSectionSize(10)
        self.table_Pipes.verticalHeader().setVisible(False)
        self.table_Pipes.verticalHeader().setDefaultSectionSize(30)
        self.table_Pipes.verticalHeader().setMinimumSectionSize(20)
        self.verticalLayout_8.addWidget(self.table_Pipes)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lbl_LoopName = QtWidgets.QLabel(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_LoopName.sizePolicy().hasHeightForWidth())
        self.lbl_LoopName.setSizePolicy(sizePolicy)
        self.lbl_LoopName.setMinimumSize(QtCore.QSize(100, 0))
        self.lbl_LoopName.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lbl_LoopName.setFont(font)
        self.lbl_LoopName.setObjectName("lbl_LoopName")
        self.gridLayout_4.addWidget(self.lbl_LoopName, 0, 0, 1, 1)
        self.btn_AddPipeToLoop = QtWidgets.QPushButton(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_AddPipeToLoop.sizePolicy().hasHeightForWidth())
        self.btn_AddPipeToLoop.setSizePolicy(sizePolicy)
        self.btn_AddPipeToLoop.setMinimumSize(QtCore.QSize(25, 0))
        self.btn_AddPipeToLoop.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_AddPipeToLoop.setFont(font)
        self.btn_AddPipeToLoop.setObjectName("btn_AddPipeToLoop")
        self.gridLayout_4.addWidget(self.btn_AddPipeToLoop, 1, 0, 1, 2)
        self.tree_Loops = QtWidgets.QTreeWidget(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_Loops.sizePolicy().hasHeightForWidth())
        self.tree_Loops.setSizePolicy(sizePolicy)
        self.tree_Loops.setMinimumSize(QtCore.QSize(150, 0))
        self.tree_Loops.setMaximumSize(QtCore.QSize(175, 5000))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tree_Loops.setFont(font)
        self.tree_Loops.setToolTipDuration(0)
        self.tree_Loops.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tree_Loops.setLineWidth(3)
        self.tree_Loops.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tree_Loops.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tree_Loops.setAlternatingRowColors(True)
        self.tree_Loops.setObjectName("tree_Loops")
        self.tree_Loops.headerItem().setText(0, "Loops")
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tree_Loops.headerItem().setFont(0, font)
        self.tree_Loops.header().setDefaultSectionSize(45)
        self.tree_Loops.header().setMinimumSectionSize(25)
        self.gridLayout_4.addWidget(self.tree_Loops, 1, 2, 7, 1, QtCore.Qt.AlignTop)
        self.le_LoopName = QtWidgets.QLineEdit(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_LoopName.sizePolicy().hasHeightForWidth())
        self.le_LoopName.setSizePolicy(sizePolicy)
        self.le_LoopName.setMinimumSize(QtCore.QSize(25, 0))
        self.le_LoopName.setMaximumSize(QtCore.QSize(100, 16777215))
        self.le_LoopName.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.le_LoopName.setFont(font)
        self.le_LoopName.setObjectName("le_LoopName")
        self.gridLayout_4.addWidget(self.le_LoopName, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(255, 242, 194);\n"
"")
        self.label_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_4.setLineWidth(3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 2, 1, 1)
        self.btn_CreateLoop = QtWidgets.QPushButton(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_CreateLoop.sizePolicy().hasHeightForWidth())
        self.btn_CreateLoop.setSizePolicy(sizePolicy)
        self.btn_CreateLoop.setMinimumSize(QtCore.QSize(25, 0))
        self.btn_CreateLoop.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_CreateLoop.setFont(font)
        self.btn_CreateLoop.setObjectName("btn_CreateLoop")
        self.gridLayout_4.addWidget(self.btn_CreateLoop, 2, 0, 1, 2)
        self.tree_LoopPipes = QtWidgets.QTreeWidget(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tree_LoopPipes.sizePolicy().hasHeightForWidth())
        self.tree_LoopPipes.setSizePolicy(sizePolicy)
        self.tree_LoopPipes.setMinimumSize(QtCore.QSize(200, 0))
        self.tree_LoopPipes.setMaximumSize(QtCore.QSize(300, 400))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tree_LoopPipes.setFont(font)
        self.tree_LoopPipes.setToolTipDuration(0)
        self.tree_LoopPipes.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tree_LoopPipes.setObjectName("tree_LoopPipes")
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tree_LoopPipes.headerItem().setFont(0, font)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tree_LoopPipes.headerItem().setFont(1, font)
        self.tree_LoopPipes.header().setDefaultSectionSize(45)
        self.tree_LoopPipes.header().setMinimumSectionSize(25)
        self.gridLayout_4.addWidget(self.tree_LoopPipes, 4, 0, 1, 2)
        self.horizontalLayout_5.addLayout(self.gridLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.label_2 = QtWidgets.QLabel(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 242, 194);\n"
"")
        self.label_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setLineWidth(3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.table_Nodes = QtWidgets.QTableWidget(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_Nodes.sizePolicy().hasHeightForWidth())
        self.table_Nodes.setSizePolicy(sizePolicy)
        self.table_Nodes.setMinimumSize(QtCore.QSize(100, 0))
        self.table_Nodes.setMaximumSize(QtCore.QSize(1000, 500))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.table_Nodes.setFont(font)
        self.table_Nodes.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.table_Nodes.setAlternatingRowColors(True)
        self.table_Nodes.setRowCount(3)
        self.table_Nodes.setObjectName("table_Nodes")
        self.table_Nodes.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.table_Nodes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.table_Nodes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.table_Nodes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.table_Nodes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.table_Nodes.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.table_Nodes.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.table_Nodes.setHorizontalHeaderItem(6, item)
        self.table_Nodes.horizontalHeader().setDefaultSectionSize(65)
        self.table_Nodes.verticalHeader().setVisible(False)
        self.table_Nodes.verticalHeader().setDefaultSectionSize(30)
        self.verticalLayout_2.addWidget(self.table_Nodes)
        self.label_3 = QtWidgets.QLabel(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 242, 194);\n"
"")
        self.label_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_3.setLineWidth(3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.tabWidget = QtWidgets.QTabWidget(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_FlowRates = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_FlowRates.sizePolicy().hasHeightForWidth())
        self.lbl_FlowRates.setSizePolicy(sizePolicy)
        self.lbl_FlowRates.setFrameShape(QtWidgets.QFrame.Panel)
        self.lbl_FlowRates.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_FlowRates.setLineWidth(3)
        self.lbl_FlowRates.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_FlowRates.setObjectName("lbl_FlowRates")
        self.horizontalLayout.addWidget(self.lbl_FlowRates, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_PipeHeadLosses = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_PipeHeadLosses.sizePolicy().hasHeightForWidth())
        self.lbl_PipeHeadLosses.setSizePolicy(sizePolicy)
        self.lbl_PipeHeadLosses.setFrameShape(QtWidgets.QFrame.Panel)
        self.lbl_PipeHeadLosses.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_PipeHeadLosses.setLineWidth(3)
        self.lbl_PipeHeadLosses.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_PipeHeadLosses.setObjectName("lbl_PipeHeadLosses")
        self.horizontalLayout_2.addWidget(self.lbl_PipeHeadLosses, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_6.setSpacing(3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_NodePressures = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_NodePressures.sizePolicy().hasHeightForWidth())
        self.lbl_NodePressures.setSizePolicy(sizePolicy)
        self.lbl_NodePressures.setFrameShape(QtWidgets.QFrame.Panel)
        self.lbl_NodePressures.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_NodePressures.setLineWidth(3)
        self.lbl_NodePressures.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_NodePressures.setObjectName("lbl_NodePressures")
        self.horizontalLayout_6.addWidget(self.lbl_NodePressures, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_7.setSpacing(3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbl_PressureAndFlowChecks = QtWidgets.QLabel(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_PressureAndFlowChecks.sizePolicy().hasHeightForWidth())
        self.lbl_PressureAndFlowChecks.setSizePolicy(sizePolicy)
        self.lbl_PressureAndFlowChecks.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_PressureAndFlowChecks.setMaximumSize(QtCore.QSize(100000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lbl_PressureAndFlowChecks.setFont(font)
        self.lbl_PressureAndFlowChecks.setFrameShape(QtWidgets.QFrame.Panel)
        self.lbl_PressureAndFlowChecks.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_PressureAndFlowChecks.setLineWidth(3)
        self.lbl_PressureAndFlowChecks.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_PressureAndFlowChecks.setObjectName("lbl_PressureAndFlowChecks")
        self.horizontalLayout_7.addWidget(self.lbl_PressureAndFlowChecks, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 2, 12, 1)
        self.lbl_EndNodeName = QtWidgets.QLabel(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_EndNodeName.sizePolicy().hasHeightForWidth())
        self.lbl_EndNodeName.setSizePolicy(sizePolicy)
        self.lbl_EndNodeName.setMinimumSize(QtCore.QSize(25, 0))
        self.lbl_EndNodeName.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lbl_EndNodeName.setFont(font)
        self.lbl_EndNodeName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_EndNodeName.setObjectName("lbl_EndNodeName")
        self.gridLayout.addWidget(self.lbl_EndNodeName, 3, 0, 1, 1)
        self.rdo_English = QtWidgets.QRadioButton(self.grp_PipeAndNodeCreation)
        self.rdo_English.setObjectName("rdo_English")
        self.gridLayout.addWidget(self.rdo_English, 7, 1, 1, 1)
        self.le_EndNodeName = QtWidgets.QLineEdit(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_EndNodeName.sizePolicy().hasHeightForWidth())
        self.le_EndNodeName.setSizePolicy(sizePolicy)
        self.le_EndNodeName.setMinimumSize(QtCore.QSize(25, 0))
        self.le_EndNodeName.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.le_EndNodeName.setFont(font)
        self.le_EndNodeName.setObjectName("le_EndNodeName")
        self.gridLayout.addWidget(self.le_EndNodeName, 3, 1, 1, 1)
        self.le_Diam = QtWidgets.QLineEdit(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_Diam.sizePolicy().hasHeightForWidth())
        self.le_Diam.setSizePolicy(sizePolicy)
        self.le_Diam.setMinimumSize(QtCore.QSize(25, 0))
        self.le_Diam.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.le_Diam.setFont(font)
        self.le_Diam.setObjectName("le_Diam")
        self.gridLayout.addWidget(self.le_Diam, 4, 1, 1, 1)
        self.btn_SavePipeNetworkFile = QtWidgets.QPushButton(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_SavePipeNetworkFile.sizePolicy().hasHeightForWidth())
        self.btn_SavePipeNetworkFile.setSizePolicy(sizePolicy)
        self.btn_SavePipeNetworkFile.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_SavePipeNetworkFile.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_SavePipeNetworkFile.setFont(font)
        self.btn_SavePipeNetworkFile.setObjectName("btn_SavePipeNetworkFile")
        self.gridLayout.addWidget(self.btn_SavePipeNetworkFile, 1, 0, 1, 2)
        self.le_StartNode = QtWidgets.QLineEdit(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_StartNode.sizePolicy().hasHeightForWidth())
        self.le_StartNode.setSizePolicy(sizePolicy)
        self.le_StartNode.setMinimumSize(QtCore.QSize(25, 0))
        self.le_StartNode.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.le_StartNode.setFont(font)
        self.le_StartNode.setObjectName("le_StartNode")
        self.gridLayout.addWidget(self.le_StartNode, 2, 1, 1, 1)
        self.lbl_Diam = QtWidgets.QLabel(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_Diam.sizePolicy().hasHeightForWidth())
        self.lbl_Diam.setSizePolicy(sizePolicy)
        self.lbl_Diam.setMinimumSize(QtCore.QSize(25, 0))
        self.lbl_Diam.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lbl_Diam.setFont(font)
        self.lbl_Diam.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Diam.setObjectName("lbl_Diam")
        self.gridLayout.addWidget(self.lbl_Diam, 4, 0, 1, 1)
        self.btn_DeletePipe = QtWidgets.QPushButton(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_DeletePipe.sizePolicy().hasHeightForWidth())
        self.btn_DeletePipe.setSizePolicy(sizePolicy)
        self.btn_DeletePipe.setMinimumSize(QtCore.QSize(25, 0))
        self.btn_DeletePipe.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_DeletePipe.setFont(font)
        self.btn_DeletePipe.setObjectName("btn_DeletePipe")
        self.gridLayout.addWidget(self.btn_DeletePipe, 6, 0, 1, 1)
        self.btn_Evaluate = QtWidgets.QPushButton(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Evaluate.sizePolicy().hasHeightForWidth())
        self.btn_Evaluate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_Evaluate.setFont(font)
        self.btn_Evaluate.setObjectName("btn_Evaluate")
        self.gridLayout.addWidget(self.btn_Evaluate, 8, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.btn_OpenPipeNetworkFile = QtWidgets.QPushButton(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_OpenPipeNetworkFile.sizePolicy().hasHeightForWidth())
        self.btn_OpenPipeNetworkFile.setSizePolicy(sizePolicy)
        self.btn_OpenPipeNetworkFile.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_OpenPipeNetworkFile.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_OpenPipeNetworkFile.setFont(font)
        self.btn_OpenPipeNetworkFile.setObjectName("btn_OpenPipeNetworkFile")
        self.gridLayout.addWidget(self.btn_OpenPipeNetworkFile, 0, 0, 1, 2)
        self.lbl_StartNode = QtWidgets.QLabel(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_StartNode.sizePolicy().hasHeightForWidth())
        self.lbl_StartNode.setSizePolicy(sizePolicy)
        self.lbl_StartNode.setMinimumSize(QtCore.QSize(25, 0))
        self.lbl_StartNode.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lbl_StartNode.setFont(font)
        self.lbl_StartNode.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_StartNode.setObjectName("lbl_StartNode")
        self.gridLayout.addWidget(self.lbl_StartNode, 2, 0, 1, 1)
        self.btn_AddPipe = QtWidgets.QPushButton(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_AddPipe.sizePolicy().hasHeightForWidth())
        self.btn_AddPipe.setSizePolicy(sizePolicy)
        self.btn_AddPipe.setMinimumSize(QtCore.QSize(25, 0))
        self.btn_AddPipe.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_AddPipe.setFont(font)
        self.btn_AddPipe.setObjectName("btn_AddPipe")
        self.gridLayout.addWidget(self.btn_AddPipe, 6, 1, 1, 1)
        self.rdo_Metric = QtWidgets.QRadioButton(self.grp_PipeAndNodeCreation)
        self.rdo_Metric.setChecked(True)
        self.rdo_Metric.setObjectName("rdo_Metric")
        self.gridLayout.addWidget(self.rdo_Metric, 7, 0, 1, 1)
        self.le_Roughness = QtWidgets.QLineEdit(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_Roughness.sizePolicy().hasHeightForWidth())
        self.le_Roughness.setSizePolicy(sizePolicy)
        self.le_Roughness.setMinimumSize(QtCore.QSize(25, 0))
        self.le_Roughness.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.le_Roughness.setFont(font)
        self.le_Roughness.setObjectName("le_Roughness")
        self.gridLayout.addWidget(self.le_Roughness, 5, 1, 1, 1)
        self.lbl_Rough = QtWidgets.QLabel(self.grp_PipeAndNodeCreation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_Rough.sizePolicy().hasHeightForWidth())
        self.lbl_Rough.setSizePolicy(sizePolicy)
        self.lbl_Rough.setMinimumSize(QtCore.QSize(25, 0))
        self.lbl_Rough.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lbl_Rough.setFont(font)
        self.lbl_Rough.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_Rough.setObjectName("lbl_Rough")
        self.gridLayout.addWidget(self.lbl_Rough, 5, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.grp_PipeAndNodeCreation, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.toolbox_SchematicAndSystemCurve = QtWidgets.QToolBox(Form)
        self.toolbox_SchematicAndSystemCurve.setObjectName("toolbox_SchematicAndSystemCurve")
        self.schematic = QtWidgets.QWidget()
        self.schematic.setGeometry(QtCore.QRect(0, 0, 1215, 1297))
        self.schematic.setObjectName("schematic")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.schematic)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.layoutGraphicsView = QtWidgets.QVBoxLayout()
        self.layoutGraphicsView.setSpacing(3)
        self.layoutGraphicsView.setObjectName("layoutGraphicsView")
        self.gv_Main = QtWidgets.QGraphicsView(self.schematic)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gv_Main.sizePolicy().hasHeightForWidth())
        self.gv_Main.setSizePolicy(sizePolicy)
        self.gv_Main.setMinimumSize(QtCore.QSize(700, 700))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.gv_Main.setFont(font)
        self.gv_Main.setMouseTracking(True)
        self.gv_Main.setToolTipDuration(100)
        self.gv_Main.setObjectName("gv_Main")
        self.layoutGraphicsView.addWidget(self.gv_Main)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_MousePosition = QtWidgets.QLabel(self.schematic)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_MousePosition.sizePolicy().hasHeightForWidth())
        self.lbl_MousePosition.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lbl_MousePosition.setFont(font)
        self.lbl_MousePosition.setFrameShape(QtWidgets.QFrame.Panel)
        self.lbl_MousePosition.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_MousePosition.setLineWidth(1)
        self.lbl_MousePosition.setObjectName("lbl_MousePosition")
        self.horizontalLayout_4.addWidget(self.lbl_MousePosition, 0, QtCore.Qt.AlignLeft)
        self.lbl_Zoom = QtWidgets.QLabel(self.schematic)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_Zoom.sizePolicy().hasHeightForWidth())
        self.lbl_Zoom.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lbl_Zoom.setFont(font)
        self.lbl_Zoom.setObjectName("lbl_Zoom")
        self.horizontalLayout_4.addWidget(self.lbl_Zoom)
        self.spnd_Zoom = QtWidgets.QDoubleSpinBox(self.schematic)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spnd_Zoom.sizePolicy().hasHeightForWidth())
        self.spnd_Zoom.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.spnd_Zoom.setFont(font)
        self.spnd_Zoom.setMinimum(0.5)
        self.spnd_Zoom.setMaximum(5.0)
        self.spnd_Zoom.setSingleStep(0.5)
        self.spnd_Zoom.setProperty("value", 1.0)
        self.spnd_Zoom.setObjectName("spnd_Zoom")
        self.horizontalLayout_4.addWidget(self.spnd_Zoom)
        self.layoutGraphicsView.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8.addLayout(self.layoutGraphicsView)
        self.toolbox_SchematicAndSystemCurve.addItem(self.schematic, "")
        self.systemCurve = QtWidgets.QWidget()
        self.systemCurve.setGeometry(QtCore.QRect(0, 0, 1215, 1297))
        self.systemCurve.setObjectName("systemCurve")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.systemCurve)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.layoutMaxFlowRate = QtWidgets.QHBoxLayout()
        self.layoutMaxFlowRate.setObjectName("layoutMaxFlowRate")
        self.lbl_MaxFlowRate = QtWidgets.QLabel(self.systemCurve)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_MaxFlowRate.sizePolicy().hasHeightForWidth())
        self.lbl_MaxFlowRate.setSizePolicy(sizePolicy)
        self.lbl_MaxFlowRate.setObjectName("lbl_MaxFlowRate")
        self.layoutMaxFlowRate.addWidget(self.lbl_MaxFlowRate)
        self.le_MaxFlowRate = QtWidgets.QLineEdit(self.systemCurve)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_MaxFlowRate.sizePolicy().hasHeightForWidth())
        self.le_MaxFlowRate.setSizePolicy(sizePolicy)
        self.le_MaxFlowRate.setObjectName("le_MaxFlowRate")
        self.layoutMaxFlowRate.addWidget(self.le_MaxFlowRate)
        self.pb_SystemCurve = QtWidgets.QPushButton(self.systemCurve)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_SystemCurve.sizePolicy().hasHeightForWidth())
        self.pb_SystemCurve.setSizePolicy(sizePolicy)
        self.pb_SystemCurve.setObjectName("pb_SystemCurve")
        self.layoutMaxFlowRate.addWidget(self.pb_SystemCurve)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layoutMaxFlowRate.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.layoutMaxFlowRate)
        self.layout_SystemCurve = QtWidgets.QVBoxLayout()
        self.layout_SystemCurve.setObjectName("layout_SystemCurve")
        self.verticalLayout_3.addLayout(self.layout_SystemCurve)
        self.toolbox_SchematicAndSystemCurve.addItem(self.systemCurve, "")
        self.horizontalLayout_3.addWidget(self.toolbox_SchematicAndSystemCurve)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(3)
        self.toolbox_SchematicAndSystemCurve.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.le_StartNode, self.le_EndNodeName)
        Form.setTabOrder(self.le_EndNodeName, self.le_Diam)
        Form.setTabOrder(self.le_Diam, self.le_Roughness)
        Form.setTabOrder(self.le_Roughness, self.btn_AddPipe)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Pipes Table"))
        self.table_Pipes.setSortingEnabled(True)
        item = self.table_Pipes.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Name"))
        item = self.table_Pipes.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Length (m)"))
        item = self.table_Pipes.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Diam (m)"))
        item = self.table_Pipes.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Rough (m)"))
        self.lbl_LoopName.setText(_translate("Form", "Loop Name"))
        self.btn_AddPipeToLoop.setText(_translate("Form", "Add Pipe(s)"))
        self.tree_Loops.setSortingEnabled(True)
        self.label_4.setText(_translate("Form", "Loops Table"))
        self.btn_CreateLoop.setText(_translate("Form", "Create Loop"))
        self.tree_LoopPipes.headerItem().setText(0, _translate("Form", "Item"))
        self.tree_LoopPipes.headerItem().setText(1, _translate("Form", "Pipe Name"))
        self.label_2.setText(_translate("Form", "Nodes Table"))
        self.table_Nodes.setSortingEnabled(True)
        item = self.table_Nodes.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Name"))
        item = self.table_Nodes.horizontalHeaderItem(1)
        item.setText(_translate("Form", "x"))
        item = self.table_Nodes.horizontalHeaderItem(2)
        item.setText(_translate("Form", "y"))
        item = self.table_Nodes.horizontalHeaderItem(3)
        item.setText(_translate("Form", "z"))
        item = self.table_Nodes.horizontalHeaderItem(4)
        item.setText(_translate("Form", "External Flow"))
        item = self.table_Nodes.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Sprinkler?"))
        item = self.table_Nodes.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Specified P/Min P"))
        self.label_3.setText(_translate("Form", "Results"))
        self.lbl_FlowRates.setText(_translate("Form", "Flow Rates"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Flow Rates"))
        self.lbl_PipeHeadLosses.setText(_translate("Form", "Pipe Head Losses"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Pipe Losses"))
        self.lbl_NodePressures.setText(_translate("Form", "Node Pressures"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Node P"))
        self.lbl_PressureAndFlowChecks.setText(_translate("Form", "Pressure and Flow Checks"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Confirmation"))
        self.lbl_EndNodeName.setText(_translate("Form", "Node 2"))
        self.rdo_English.setText(_translate("Form", "English"))
        self.le_EndNodeName.setText(_translate("Form", "b"))
        self.le_Diam.setText(_translate("Form", "300"))
        self.btn_SavePipeNetworkFile.setText(_translate("Form", "Save Pipe Network File"))
        self.le_StartNode.setText(_translate("Form", "a"))
        self.lbl_Diam.setText(_translate("Form", "Diam (mm)"))
        self.btn_DeletePipe.setText(_translate("Form", "Delete Pipe"))
        self.btn_Evaluate.setText(_translate("Form", "Evaluate Pipe Network"))
        self.btn_OpenPipeNetworkFile.setText(_translate("Form", "Open Pipe Network File"))
        self.lbl_StartNode.setText(_translate("Form", "Node 1"))
        self.btn_AddPipe.setText(_translate("Form", "Add Pipe"))
        self.rdo_Metric.setText(_translate("Form", "Metric"))
        self.le_Roughness.setText(_translate("Form", "0.00025"))
        self.lbl_Rough.setText(_translate("Form", "Roughness (m)"))
        self.lbl_MousePosition.setText(_translate("Form", "Mouse Position:"))
        self.lbl_Zoom.setText(_translate("Form", "Scale"))
        self.toolbox_SchematicAndSystemCurve.setItemText(self.toolbox_SchematicAndSystemCurve.indexOf(self.schematic), _translate("Form", "Schematic"))
        self.lbl_MaxFlowRate.setText(_translate("Form", "Max. Flow Rate (L/S)"))
        self.le_MaxFlowRate.setText(_translate("Form", "15.0"))
        self.pb_SystemCurve.setText(_translate("Form", "Calc Sys Curve"))
        self.toolbox_SchematicAndSystemCurve.setItemText(self.toolbox_SchematicAndSystemCurve.indexOf(self.systemCurve), _translate("Form", "System Curve"))

